; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.1"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.8"

projects[service_links][subdir] = "contrib"
projects[service_links][version] = "2.2"

projects[boxes][subdir] = "contrib"
projects[boxes][version] = "1.2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.6"

projects[context][subdir] = "contrib"
projects[context][version] = "3.6"

projects[delta][subdir] = "contrib"
projects[delta][version] = "3.0-beta11"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[media][subdir] = "contrib"
projects[media][version] = "1.4"

projects[styles][subdir] = "contrib"
projects[styles][version] = "2.0-alpha8"

projects[flag][subdir] = "contrib"
projects[flag][version] = "2.2"

projects[galleryformatter][subdir] = "contrib"
projects[galleryformatter][version] = "1.3"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.4"

projects[insert][subdir] = "contrib"
projects[insert][version] = "1.3"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[menu_position][subdir] = "contrib"
projects[menu_position][version] = "1.1"

projects[nodequeue][subdir] = "contrib"
projects[nodequeue][version] = "2.0-beta1"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[rotating_banner][subdir] = "contrib"
projects[rotating_banner][version] = "2.x-dev"

projects[stage_file_proxy][subdir] = "development"
projects[stage_file_proxy][version] = "1.6"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.2"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[omega][subdir] = "contrib"
projects[omega][version] = "4.3"

; Profiler
libraries[profiler][download][type] = "git"
libraries[profiler][download][branch] = "7.x-2.x"
libraries[profiler][download][revision] = "2ed2140"
